name: domain
description: Domain layer of Flutter Covid19 India app
# version: 1.0.0

environment:
  sdk: '>=2.8.1 <3.0.0'

#dependencies:
#  path: ^1.7.0

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
