name: domain
description: Domain layer of Flutter Covid19 India app
# version: 1.0.0

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  rxdart: ^0.24.0
  either_option: ^1.0.6
  meta: ^1.1.8
#  path: ^1.7.0

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
