
enum StateUT {
  jk,
  wb,
  ut,
  up,
  tr,
  tn,
  tg,
  sk,
  rj,
  py,
  pb,
  or,
  nl,
  mz,
  mp,
  mn,
  ml,
  mh,
  ld,
  kl,
  ka,
  lk,
  jh,
  hr,
  hp,
  gj,
  ga,
  dn,
  dl,
  dd,
  ct,
  ch,
  br,
  as,
  ar,
  ap,
  an
}

final Map<StateUT, String> kStateNamesMap = {
  StateUT.jk: 'Jammu and Kashmir',
  StateUT.wb: 'West Bengal',
  StateUT.ut: 'Uttarakhand',
  StateUT.up: 'Uttar Pradesh',
  StateUT.tr: 'Tripura',
  StateUT.tn: 'Tamil Nadu',
  StateUT.tg: 'Telangana',
  StateUT.sk: 'Sikkim',
  StateUT.rj: 'Rajasthan',
  StateUT.py: 'Puducherry',
  StateUT.pb: 'Punjab',
  StateUT.or: 'Odisha',
  StateUT.nl: 'Nagaland',
  StateUT.mz: 'Mizoram',
  StateUT.mp: 'Madhya Pradesh',
  StateUT.mn: 'Manipur',
  StateUT.ml: 'Meghalaya',
  StateUT.mh: 'Maharashtra',
  StateUT.ld: 'Ladakh',
  StateUT.lk: 'Lakshadweep',
  StateUT.kl: 'Kerala',
  StateUT.ka: 'Karnataka',
  StateUT.jh: 'Jharkhand',
  StateUT.hr: 'Haryana',
  StateUT.hp: 'Himachal Pradesh',
  StateUT.gj: 'Gujarat',
  StateUT.ga: 'Goa',
  StateUT.dn: 'Dadra and Nagar Haveli and Daman and Diu',
  StateUT.dl: 'Delhi',
  StateUT.dd: 'Dadra and Nagar Haveli and Daman and Diu',
  StateUT.ct: 'Chhattisgarh',
  StateUT.ch: 'Chandigarh',
  StateUT.br: 'Bihar',
  StateUT.as: 'Assam',
  StateUT.ar: 'Arunachal Pradesh',
  StateUT.ap: 'Andhra Pradesh',
  StateUT.an: 'Andaman and Nicobar Islands',
};